# app/config/application.yml
defaults: &defaults
  
  copyright: d.k.d Internet Service GmbH
  
  reputation:
    answer:
      up: 10
      down: -10
      penalty: -2
      accept: 30
      reject: -30
      
    comment:
      up: 5
      down: -5
      penalty: -2
    
    question:
      up: 10
      down: -10
      penalty: -4  
  
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults