# app/config/application.yml
defaults: &defaults
  
  copyright: d.k.d Internet Service GmbH
  
  syntax_highlighting:
    languages: "ruby, php, html-xml, typoscript"
  
  questions:
    restrict_access: true
  
  user:
    restrict_access: true
  
  mailer:
    from: do-not-reply@smartr.localhost
  
  reputation:
    answer:
      up: 10
      down: -10
      penalty: -2
      accept: 30
      reject: -30
      
    comment:
      up: 5
      down: -5
      penalty: -2
    
    question:
      up: 10
      down: -10
      penalty: -4
      new: 5 

development:
  host: http://localhost:3000
  <<: *defaults

test:
  host: http://localhost:3000
  <<: *defaults

production:
  host: http://smartr.dkd.de
  <<: *defaults